# Sales Performance Analysis

## Business Objective

Analyze global sales data to understand revenue performance, profitability drivers, customer behavior, and opportunities for business improvement.

## Tools Used

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Power BI

## Dataset

Global retail sales dataset containing 51,290 transactions across different markets, regions, customers, products, and categories.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option("display.max_columns", None)

In [2]:
df= pd.read_csv('SuperStore_Orders.csv',encoding="latin1")
#df = pd.read_excel("SuperStore_Orders.xlsx")

In [3]:
df.head()

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,product_id,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,1/1/2011,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,OFF-TEN-10000025,Office Supplies,Storage,"Tenex Lockers, Blue",408,2,0.0,106.140,35.46,Medium,2011
1,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,OFF-SU-10000618,Office Supplies,Supplies,"Acme Trimmer, High Speed",120,3,0.1,36.036,9.72,Medium,2011
2,HU-2011-1220,1/1/2011,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,OFF-TEN-10001585,Office Supplies,Storage,"Tenex Box, Single Width",66,4,0.0,29.640,8.17,High,2011
3,IT-2011-3647632,1/1/2011,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,OFF-PA-10001492,Office Supplies,Paper,"Enermax Note Cards, Premium",45,3,0.5,-26.055,4.82,High,2011
4,IN-2011-47883,1/1/2011,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,FUR-FU-10003447,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114,5,0.1,37.770,4.70,Medium,2011

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        51290 non-null  object
 1   order_date      51290 non-null  object
 2   ship_date       51290 non-null  object
 3   ship_mode       51290 non-null  object
 4   customer_name   51290 non-null  object
 5   segment         51290 non-null  object
 6   state           51290 non-null  object
 7   country         51290 non-null  object
 8   market          51290 non-null  object
 9   region          51290 non-null  object
 10  product_id      51290 non-null  object
 11  category        51290 non-null  object
 12  sub_category    51290 non-null  object
 13  product_name    51290 non-null  object
 14  sales           51290 non-null  object
 15  quantity        51290 non-null  int64
 16  discount        51290 non-null  float64
 17  profit          51290 non-null  float64
 18  shipping_cost   51290 non-null  float64
 19  order_priority  51290 non-null  object
 20  year            51290 non-null  int64
dtypes: float64(3), int64(2), object(16)
memory usage: 8.2+ MB

In [5]:
df.shape

(51290, 21)

In [6]:
df.describe()

           quantity      discount        profit  shipping_cost          year
count  51290.000000  51290.000000  51290.000000   51290.000000  51290.000000
mean       3.476545      0.142908     28.641740      26.375915   2012.777208
std        2.278766      0.212280    174.424113      57.296804      1.098931
min        1.000000      0.000000  -6599.978000       0.000000   2011.000000
25%        2.000000      0.000000      0.000000       2.610000   2012.000000
50%        3.000000      0.000000      9.240000       7.790000   2013.000000
75%        5.000000      0.200000     36.810000      24.450000   2014.000000
max       14.000000      0.850000   8399.976000     933.570000   2014.000000

In [7]:
df.columns

Index(['order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'state', 'country', 'market', 'region', 'product_id',
       'category', 'sub_category', 'product_name', 'sales', 'quantity',
       'discount', 'profit', 'shipping_cost', 'order_priority', 'year'],
      dtype='object')

The dataset contains 51,290 sales records and 21 columns including order details, customer information, product details, sales, profit, and shipping information.

In [8]:
df["sales"] = (
    df["sales"]
    .astype(str)
    .str.replace(",", "")
    .astype(float)
)

In [9]:
df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="mixed",
    dayfirst=True
)

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="mixed",
    dayfirst=True
)

In [10]:
df["shipping_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [11]:
df["shipping_days"].describe()

count    51290.000000
mean         3.969370
std          1.729437
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: shipping_days, dtype: float64

Shipping days was created to measure delivery time and allow future analysis of logistics performance.

In [12]:
total_sales = df["sales"].sum()
total_profit = df["profit"].sum()

profit_margin = (
    total_profit / total_sales
) * 100

total_orders = df["order_id"].nunique()

total_customers = df["customer_name"].nunique()

average_order_value = (
    total_sales / total_orders
)

In [13]:
print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Profit Margin:", profit_margin)
print("Orders:", total_orders)
print("Customers:", total_customers)
print("Average Order Value:", average_order_value)

Total Sales: 12642905.0
Total Profit: 1469034.8212799998
Profit Margin: 11.61944047890892
Orders: 25035
Customers: 795
Average Order Value: 505.0091871380068

# Market Performance Analysis

In [14]:
market_analysis = df.groupby("market").agg(
    total_sales=("sales", "sum"),
    total_profit=("profit", "sum"),
    orders=("order_id", "nunique")
)

market_analysis

        total_sales  total_profit  orders
market
APAC      3585833.0  437577.57900    5437
Africa     783776.0   88871.63100    2232
Canada      66932.0   17817.39000     201
EMEA       806184.0   43897.97100    2462
EU        2938139.0  372829.74150    4593
LATAM     2164687.0  221643.48708    5138
US        2297354.0  286397.02170    5009

In [15]:
market_analysis.sort_values(
    by="total_sales",
    ascending=False
)

        total_sales  total_profit  orders
market
APAC      3585833.0  437577.57900    5437
EU        2938139.0  372829.74150    4593
US        2297354.0  286397.02170    5009
LATAM     2164687.0  221643.48708    5138
EMEA       806184.0   43897.97100    2462
Africa     783776.0   88871.63100    2232
Canada      66932.0   17817.39000     201

In [16]:
market_analysis["profit_margin"] = (
    market_analysis["total_profit"] /
    market_analysis["total_sales"]
) * 100

market_analysis.sort_values(
    by="profit_margin",
    ascending=False
)

        total_sales  total_profit  orders  profit_margin
market
Canada      66932.0   17817.39000     201      26.620137
EU        2938139.0  372829.74150    4593      12.689316
US        2297354.0  286397.02170    5009      12.466386
APAC      3585833.0  437577.57900    5437      12.202955
Africa     783776.0   88871.63100    2232      11.338907
LATAM     2164687.0  221643.48708    5138      10.239055
EMEA       806184.0   43897.97100    2462       5.445155

# Category Profitability Analysis

In [17]:
category_analysis = df.groupby("category").agg(
    total_sales=("sales", "sum"),
    total_profit=("profit", "sum"),
    orders=("order_id", "nunique")
)

category_analysis["profit_margin"] = (
    category_analysis["total_profit"] /
    category_analysis["total_sales"]
) * 100

category_analysis.sort_values(
    by="total_profit",
    ascending=False
)

                 total_sales  total_profit  orders  profit_margin
category
Technology         4744691.0  663778.73318    8354      13.989925
Office Supplies    3787330.0  518473.83430   19003      13.689693
Furniture          4110884.0  286782.25380    8195       6.976170

# Product Performance Analysis

In [18]:
product_analysis = df.groupby("product_name").agg(
    total_sales=("sales", "sum"),
    total_profit=("profit", "sum"),
    quantity=("quantity", "sum")
)

product_analysis.sort_values(
    by="total_sales",
    ascending=False
).head(10)

,total_sales,total_profit,quantity
product_name,,,
"Apple Smart Phone, Full Size",86936.0,5921.5786,171
"Cisco Smart Phone, Full Size",76441.0,17238.5206,139
"Motorola Smart Phone, Full Size",73159.0,17027.1130,134
"Nokia Smart Phone, Full Size",71904.0,9938.1955,147
Canon imageCLASS 2200 Advanced Copier,61600.0,25199.9280,20
"Hon Executive Leather Armchair, Adjustable",58200.0,5997.2541,169
"Office Star Executive Leather Armchair, Adjustable",50667.0,4710.9840,141
"Harbour Creations Executive Leather Armchair, Adjustable",50120.0,10427.3260,142
"Samsung Smart Phone, Cordless",48654.0,-198.0900,108
"Nokia Smart Phone, with Caller ID",47880.0,9465.3257,96

# Discount Impact Analysis

In [19]:
discount_analysis = df.groupby("discount").agg(
    total_sales=("sales", "sum"),
    total_profit=("profit", "sum"),
    orders=("order_id", "nunique")
)

discount_analysis

          total_sales  total_profit  orders
discount
0.000       6992734.0  1.770695e+06   15211
0.002        261395.0  5.797658e+04     437
0.070        121620.0  2.114850e+04     135
0.100       1579618.0  2.606417e+05    2456
0.150        306037.0  2.737590e+04     477
0.170        247404.0  2.816307e+04     519
0.200       1203855.0  1.177159e+05    3389
0.202         16213.0 -5.952727e+02      39
0.250         88063.0  8.005875e+02     154
0.270         89351.0 -1.675079e+03     329
0.300        188913.0 -1.968585e+04     321
0.320         14491.0 -2.391138e+03      27
0.350         95704.0 -1.416965e+04     114
0.370         31615.0 -5.806202e+03      64
0.400        559557.0 -1.437485e+05    1870
0.402         33737.0 -1.143045e+04     100
0.450         33397.0 -1.360679e+04     215
0.470         83432.0 -3.116225e+04     525
0.500        324145.0 -1.586299e+05     918
0.550          6308.0 -3.150672e+03      10
0.570          8144.0 -6.313548e+03      12
0.600        184586.0 -1.639547e+05    1068
0.602          4977.0 -4.905419e+03      21
0.650          6580.0 -6.221966e+03      16
0.700        139770.0 -1.863505e+05    1037
0.800         20462.0 -3.861623e+04     266
0.850           797.0 -3.068658e+03       2

In [20]:
loss_analysis = df[df["profit"] < 0].groupby("discount").agg(
    loss_sales=("sales", "sum"),
    total_loss=("profit", "sum"),
    orders=("order_id", "nunique")
)

loss_analysis.sort_values(
    by="total_loss"
)

          loss_sales    total_loss  orders
discount
0.700       139770.0 -186350.48290    1037
0.600       184586.0 -163954.68720    1068
0.500       322470.0 -158629.87810     912
0.400       456425.0 -152963.62680    1639
0.800        20462.0  -38616.22520     266
0.200       293811.0  -37548.38940     904
0.470        79653.0  -31306.22580     506
0.300       149960.0  -23699.41690     266
0.350        65248.0  -18046.88400      83
0.100       326604.0  -16974.14740     757
0.450        31878.0  -13700.34160     199
0.402        30631.0  -11613.37768      88
0.150       113255.0   -8779.88600     190
0.270        47585.0   -8543.06760     178
0.170        74358.0   -7033.95450     209
0.370        20919.0   -6931.68450      44
0.250        44406.0   -6763.67250      86
0.570         8144.0   -6313.54800      12
0.650         6580.0   -6221.96550      16
0.602         4977.0   -4905.41896      21
0.550         6308.0   -3150.67200      10
0.850          797.0   -3068.65800       2
0.320        14491.0   -2391.13770      27
0.202        11041.0   -1714.53620      24
0.070        22747.0   -1116.99900      30
0.002         9235.0     -18.50728      13

# Final Business Recommendations

1. Reduce excessive discounts because discounts above 40% significantly reduce profitability.

2. Increase focus on Technology products due to strong profit margins.

3. Investigate Furniture profitability because sales are high but margins are lower.

4. Analyze EMEA performance because it has the weakest profit margin.

5. Promote high-profit products instead of only high-volume products.

In [21]:
df.to_csv("sales_cleaned_final.csv", index=False)